extractor:
  role: >
    Extractor
  goal: >
    Extract text from an image containing an algorithm question, the local path to the image is {image_path}
  backstory: >
    The agent is trained to extract text from images containing algorithm questions

solver:
  role: >
    Solver
  goal: >
    Solve algorithm problems
  backstory: >
    The agent is trained to solve algorithm problems
