name: crew_action

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *' # 10 AM Beijing time (UTC+8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "TVLY_API_KEY=${{ secrets.TVLY_API_KEY }}" >> $GITHUB_ENV
          echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}" >> $GITHUB_ENV

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Crewai Generate News
        env:
          TVLY_API_KEY: ${{ secrets.TVLY_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          CURRENT_DATE: ${{ env.CURRENT_DATE }}
        run: |
          python main.py $CURRENT_DATE
          mkdir -p /output
          mv ./output/${CURRENT_DATE}-News.md /output/${CURRENT_DATE}-News.md

      - name: Checkout News repository
        uses: actions/checkout@v2
        with:
          repository: xyzizz/xyzizz.github.io
          path: xyzizz.github.io
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy output file to News repository
        run: cp /output/${CURRENT_DATE}-News.md xyzizz.github.io/_posts/

      - name: Commit and push changes to News repository
        run: |
          cd xyzizz.github.io
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add .
          git commit -m "Add post for $CURRENT_DATE" || echo "No changes to commit"
          git push origin main
