name: crew_action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "TYLV_API_KEY=${{ secrets.TYLV_API_KEY }}" >> $GITHUB_ENV
          echo "TYLV_API_KEY=${{ secrets.ZHIPU_API_KEY }}" >> $GITHUB_ENV

      - name: Get current date
        id: get_date  # 添加 id 以便引用输出
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Crew run
        env:
          TYLV_API_KEY: ${{ secrets.TYLV_API_KEY }}
          ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
        run: python main.py
